taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
taskkill /f /im mscript.exe
